# Generated by Django 5.1.5 on 2026-05-28 01:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrawingMetadataExtractionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("elapsed_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("warnings_json", models.JSONField(blank=True, default=list)),
                ("extractor_name", models.CharField(blank=True, max_length=128)),
                ("extractor_version", models.CharField(blank=True, max_length=64)),
                ("schema_version", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegisteredDrawing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("host_drawing_id", models.CharField(blank=True, max_length=255)),
                ("filename", models.CharField(max_length=255)),
                ("source_path", models.CharField(max_length=1024)),
                ("source_format", models.CharField(default="icad", max_length=64)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[("2d", "2D"), ("3d", "3D")], max_length=8
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DrawingMetadataSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_extract_json", models.JSONField(blank=True, default=dict)),
                (
                    "canonical_attributes_json",
                    models.JSONField(blank=True, default=dict),
                ),
                ("derived_tags_json", models.JSONField(blank=True, default=list)),
                ("manual_overrides_json", models.JSONField(blank=True, default=dict)),
                ("normalizer_version", models.CharField(blank=True, max_length=32)),
                ("tag_rule_version", models.CharField(blank=True, max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=255)),
                (
                    "latest_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="drawing_metadata.drawingmetadataextractionjob",
                    ),
                ),
                (
                    "drawing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot",
                        to="drawing_metadata.registereddrawing",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="drawingmetadataextractionjob",
            name="drawing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="drawing_metadata.registereddrawing",
            ),
        ),
        migrations.CreateModel(
            name="DrawingMetadataAuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("extraction", "Extraction"),
                            ("override", "Override"),
                            ("requeue", "Requeue"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("before_json", models.JSONField(blank=True, default=dict)),
                ("after_json", models.JSONField(blank=True, default=dict)),
                ("executed_by", models.CharField(blank=True, max_length=255)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drawing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="drawing_metadata.registereddrawing",
                    ),
                ),
            ],
            options={
                "ordering": ["-executed_at"],
            },
        ),
    ]
