# Generated by Django 5.1.5 on 2026-07-17 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drawing_metadata", "0002_mode_aware_refactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawingmetadataauditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("extraction", "Extraction"),
                    ("override", "Override"),
                    ("requeue", "Requeue"),
                    ("re_normalize", "ReNormalize"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="DrawingComposedMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canonical_attributes_json",
                    models.JSONField(blank=True, default=dict),
                ),
                ("derived_tags_json", models.JSONField(blank=True, default=list)),
                ("conflicts_json", models.JSONField(blank=True, default=list)),
                ("normalizer_version", models.CharField(blank=True, max_length=32)),
                ("tag_rule_version", models.CharField(blank=True, max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drawing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composed_metadata",
                        to="drawing_metadata.registereddrawing",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TagDictionaryEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("customer", "客先"),
                            ("equipment_category", "装置カテゴリ"),
                            ("maker", "メーカー"),
                            ("spec", "規格"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("canonical_value", models.CharField(max_length=255)),
                ("aliases_json", models.JSONField(blank=True, default=list)),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="小さいほど優先。複数候補時の主候補選択順。",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["kind", "priority", "canonical_value"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "canonical_value"),
                        name="tag_dictionary_unique_kind_value",
                    )
                ],
            },
        ),
    ]
