# Generated by Django 5.1.5 on 2026-07-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drawing_metadata", "0005_registered_drawing_content_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagDictionaryEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("customer", "客先"),
                            ("equipment_category", "装置カテゴリ"),
                            ("project", "案件"),
                            ("maker", "メーカー"),
                            ("spec", "規格"),
                            ("heat_treatment", "熱処理"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "canonical_value",
                    models.CharField(
                        help_text="タグ・属性に使う正規名(例: コマツ小山)",
                        max_length=255,
                    ),
                ),
                (
                    "aliases_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="照合に使う別名・略名のリスト",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="小さいほど優先。複数一致時の主候補選択順。",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["kind", "priority", "canonical_value"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "canonical_value"),
                        name="tag_dictionary_unique_kind_value",
                    )
                ],
            },
        ),
    ]
